#!/bin/sh

# BLAST on the NT database. To use a different DB, just provide a toolbox
# with an edited script.

# Note for regular QC we use "-task dc-megablast" but that seems to break things here?!

exec /lustre/software/blast+/ncbi-blast-2.6.0+/bin/blastn  \
    -db /lustre/references/blastdb/nt-20190719/nt "$@"
