#!/bin/sh

# BLAST on the NT database. To use a different DB, just provide a toolbox
# with an edited script.

# Note for regular QC we use "-task dc-megablast" but that seems to break things here?!
BASE="/mnt/lustre/e1000/home/edg01/edg01/shared"

exec "$BASE"/software/blast+/ncbi-blast-2.12.0+/bin/blastn \
    -db "$BASE"/references/blastdb/nt-20190719/nt "$@"
