#!/bin/sh

# BLAST on the Landmark database. Useful for testing cos it's small and fast,
# but still produces meaningful results.

# Note we should look at SmartBLAST, probably.
BASE="/mnt/lustre/e1000/home/edg01/edg01/shared"

exec "$BASE"/software/blast+/ncbi-blast-2.12.0+/bin/blastx \
    -db "$BASE"/references/blastdb/landmark-2021-10-05/landmark "$@"
