#!/bin/sh

# Run the right blobtools with the right Python
export PATH="/lustre/software/python/current/bin:$PATH"
export PATH="/lustre/software/blobtools/current_patched2:$PATH"

exec blobtools "$@"
