DEFAULTS:
    CLUSTER_QUEUE: edgen-global
    EXTRA_SLURM_FLAGS: ''
drmaa: >-
    -p {CLUSTER_QUEUE} --qos=edgen
    --time={{resources.time_h}}:00:00
    --mem={{resources.mem_gb}}000 --mincpus={{resources.n_cpus}}
    -e slurm_output/slurm_job.{{rule}}.%A.err
    -o slurm_output/slurm_job.{{rule}}.%A.out
    {EXTRA_SLURM_FLAGS}
jobname: '{{rulename}}.snakejob.{{jobid}}.sh'
jobscript: '{TOOLBOX}/snakemake_jobscript.sh'
group-components:
    - a_cluster_job=10
    - a_cluster_job2=10
printshellcmds: true
rerun-incomplete: true
keep-going: true
resources:
    - nfscopy=1
    - local_thread=2
set-resource-scopes:
    - local_thread=local
jobs: 100
local-cores: 4
latency-wait: 10
default-resources:
    - tmpdir='/lustre-gseg/tmp'
    - time_h=24
    - mem_gb=6
    - n_cpus=1
