DEFAULTS:
    CLUSTER_QUEUE: edgen-global
    EXTRA_SLURM_FLAGS: ''
drmaa: >-
    -p {CLUSTER_QUEUE} --qos=edgen
    --time={{resources.time_h}}:00:00
    --mem={{resources.mem_mb}} --mincpus={{resources.n_cpus}}
    -e slurm_output/{{rule}}.%A.err
    -o slurm_output/{{rule}}.%A.out
    {EXTRA_SLURM_FLAGS}
jobname: '{{rulename}}.snakejob.{{jobid}}.sh'
jobscript: '{TOOLBOX}/snakemake_jobscript.sh'
printshellcmds: true
rerun-incomplete: true
keep-going: true
resources:
    - nfscopy=1
jobs: 200
cores: 400
local-cores: 4
latency-wait: 10
default-resources:
    - tmpdir='/lustre-gseg/tmp'
    - time_h=24
    - mem_mb=6000
    - n_cpus=1
